# backend/services/mock_gemini.py
"""Mock of `services.gemini_service.GeminiService` for demo mode.

Returns realistic, schema-compatible structured responses for the Observer,
Diagnosis, Repair and Validation agents without calling Vertex AI — used as a
fallback when no GCP credentials / Vertex AI access are configured.
"""
from __future__ import annotations

import random
import re
from typing import Any

from api.config import Settings

# RootCauseCategory mapped from FailureType (see api/schemas/diagnosis.py / trace.py)
_FAILURE_TO_ROOT_CAUSE: dict[str, tuple[str, str]] = {
    "tool_error": ("tool_configuration", "A tool invocation failed due to an invalid parameter, expired credential, or upstream API error, and the agent had no fallback or retry path."),
    "hallucination": ("model_limitation", "The model produced output not grounded in the retrieved context or tool results, fabricating details that were never present in the input."),
    "staleness": ("data_quality", "The agent acted on stale cached data instead of refetching from the source of truth, leading to a decision based on outdated state."),
    "loop": ("orchestration_logic", "The agent's control loop lacked a termination condition, causing it to repeat the same tool call until the step/iteration budget was exhausted."),
    "timeout": ("resource_constraint", "An upstream call exceeded its timeout budget under load, and the orchestration had no circuit breaker to fail fast."),
    "context_overflow": ("context_management", "The conversation/context window exceeded the model's token limit, silently truncating earlier instructions and tool outputs."),
    "safety_violation": ("security_policy", "The model's safety filter rejected the request or response, halting execution without a graceful fallback."),
    "planning_failure": ("prompt_design", "The system prompt under-specified the task decomposition, so the planner produced an incomplete or incorrectly ordered plan."),
    "retrieval_failure": ("external_service", "The retrieval/search backend returned no relevant results or errored, and the agent proceeded without grounding."),
    "none": ("unknown", "No clear failure signal was present in the trace; manual review recommended."),
}

_SEVERITY_BY_FAILURE: dict[str, str] = {
    "tool_error": "high",
    "hallucination": "critical",
    "staleness": "medium",
    "loop": "high",
    "timeout": "medium",
    "context_overflow": "high",
    "safety_violation": "critical",
    "planning_failure": "medium",
    "retrieval_failure": "medium",
    "none": "low",
}


class MockGeminiService:
    """Drop-in replacement for GeminiService — no Vertex AI / ADC required."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    # ── Public API (mirrors GeminiService) ─────────────────────────────────

    async def generate_text(
        self,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> str:
        return (
            "[DEMO MODE] Gemini analysis is simulated because no Vertex AI "
            "credentials are configured for this deployment. This response "
            "was generated by TRACE-X's built-in heuristic engine."
        )

    async def generate_structured(
        self,
        prompt: str,
        system_instruction: str | None = None,
        response_schema: dict | None = None,
        temperature: float = 0.2,
    ) -> dict[str, Any]:
        sysi = system_instruction or ""

        if "Diagnosis Agent" in sysi:
            return self._diagnosis_response(prompt)
        if "Observer Agent" in sysi:
            return self._observation_response(prompt)
        if "QA engineer validating" in sysi:
            return self._validation_response()
        if "Repair Agent" in sysi:
            return self._repair_response(prompt)

        return {}

    async def generate_with_tools(
        self,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]],
        system_instruction: str | None = None,
    ) -> dict[str, Any]:
        return {
            "text": "[DEMO MODE] Tool-calling is simulated; no Vertex AI credentials configured.",
            "tool_calls": [],
        }

    async def estimate_tokens(self, text: str) -> int:
        return max(1, len(text) // 4)

    async def summarize(self, text: str, max_sentences: int = 3) -> str:
        sentences = re.split(r"(?<=[.!?])\s+", text.strip())
        return " ".join(s for s in sentences[:max_sentences] if s)

    async def generate_incident_report(
        self,
        trace: Any,
        diagnosis: Any | None,
        repair: Any | None,
    ) -> str:
        """Build a deterministic markdown postmortem from a trace/diagnosis/repair."""
        failure_type = trace.failure_type.value if trace.failure_type else "none"
        failing_span = trace.spans[-1] if trace.spans else None
        duration_s = (trace.duration_ms or 0) / 1000

        lines: list[str] = [
            f"# Incident Report — {trace.agent_name}",
            "",
            "_[DEMO MODE] This report was generated by TRACE-X's built-in heuristic "
            "engine because no Vertex AI credentials are configured._",
            "",
            "## Summary",
            f"- **Trace ID:** `{trace.trace_id}`",
            f"- **Agent:** {trace.agent_name} (`{trace.agent_id}`, v{trace.agent_version or 'unknown'})",
            f"- **Status:** {trace.status.value if hasattr(trace.status, 'value') else trace.status}",
            f"- **Failure type:** {failure_type.replace('_', ' ')}",
            f"- **Started:** {trace.started_at.isoformat() if trace.started_at else 'unknown'}",
            f"- **Duration:** {duration_s:.2f}s across {len(trace.spans)} spans",
        ]

        if trace.failure_reason:
            lines += ["", "## What Happened", trace.failure_reason]

        if failing_span:
            lines += [
                "",
                "## Failing Span",
                f"- **Span:** `{failing_span.span_name}` ({failing_span.kind.value if hasattr(failing_span.kind, 'value') else failing_span.kind})",
                f"- **Error:** {failing_span.error_type or 'unknown'} — {failing_span.error_message or 'no message'}",
            ]

        if diagnosis:
            lines += [
                "",
                "## Root Cause Analysis",
                f"- **Category:** {diagnosis.root_cause_category.value.replace('_', ' ')}",
                f"- **Severity:** {diagnosis.severity.value}",
                f"- **Confidence:** {diagnosis.confidence:.0%}",
                "",
                diagnosis.evidence_summary or diagnosis.root_cause_description,
            ]

            if diagnosis.immediate_actions:
                lines += ["", "## Immediate Actions"]
                lines += [f"- {a}" for a in diagnosis.immediate_actions]

            if diagnosis.long_term_recommendations:
                lines += ["", "## Long-Term Recommendations"]
                lines += [f"- {r}" for r in diagnosis.long_term_recommendations]
        else:
            lines += ["", "## Root Cause Analysis", "_No diagnosis is available for this trace yet._"]

        if repair:
            status_val = repair.status.value if hasattr(repair.status, "value") else repair.status
            lines += [
                "",
                "## Remediation",
                f"- **Repair:** {repair.title}",
                f"- **Type:** {repair.repair_type.value.replace('_', ' ')}",
                f"- **Status:** {status_val}",
                f"- **Confidence:** {repair.confidence:.0%}",
            ]
            if repair.validation_passed is not None:
                outcome = "PASSED" if repair.validation_passed else "FAILED"
                score = f" (score {repair.validation_score:.0%})" if repair.validation_score is not None else ""
                lines.append(f"- **Validation:** {outcome}{score}")
            lines += ["", repair.description]
        else:
            lines += ["", "## Remediation", "_No repair has been generated for this trace yet._"]

        return "\n".join(lines)

    # ── Response generators ─────────────────────────────────────────────────

    def _diagnosis_response(self, prompt: str) -> dict[str, Any]:
        agent_name = _extract(prompt, r"Agent:\s*(.+?)\s*\(ID:") or "the agent"
        failure_type = (_extract(prompt, r"Failure Type:\s*(\w+)") or "none").lower()
        failing_span_id = _extract(prompt, r"Span ID:\s*(\S+)")

        root_cause_category, root_cause_description = _FAILURE_TO_ROOT_CAUSE.get(
            failure_type, _FAILURE_TO_ROOT_CAUSE["none"]
        )
        severity = _SEVERITY_BY_FAILURE.get(failure_type, "medium")
        confidence = round(random.uniform(0.72, 0.93), 2)

        evidence_spans = [failing_span_id] if failing_span_id else []

        return {
            "root_cause_category": root_cause_category,
            "root_cause_description": (
                f"[DEMO] {root_cause_description} Observed in {agent_name} "
                f"(failure type: {failure_type})."
            ),
            "severity": severity,
            "confidence": confidence,
            "reasoning_chain": [
                {
                    "step_number": 1,
                    "hypothesis": f"The {failure_type.replace('_', ' ')} failure originates in the final execution spans.",
                    "evidence": [
                        f"Trace status is FAILURE with failure_type={failure_type}",
                        "Error spans present in the last steps of the execution timeline",
                    ],
                    "evidence_spans": evidence_spans,
                    "confidence": confidence,
                    "conclusion": f"Failure pattern is consistent with a {root_cause_category.replace('_', ' ')} issue.",
                    "eliminated_alternatives": ["model_limitation" if root_cause_category != "model_limitation" else "prompt_design"],
                },
                {
                    "step_number": 2,
                    "hypothesis": "The agent had no recovery path once the failure occurred.",
                    "evidence": ["No retry or fallback span follows the failing span"],
                    "evidence_spans": evidence_spans,
                    "confidence": round(max(confidence - 0.1, 0.5), 2),
                    "conclusion": "Lack of error handling escalated a recoverable error into a trace failure.",
                    "eliminated_alternatives": [],
                },
            ],
            "failing_span_id": failing_span_id,
            "divergence_point_span_id": failing_span_id,
            "contributing_spans": evidence_spans,
            "evidence_summary": (
                f"[DEMO] {agent_name} failed with `{failure_type}`. Root cause classified as "
                f"`{root_cause_category}`. {root_cause_description}"
            ),
            "blast_radius": {
                "affected_agents": [],
                "downstream_services": [],
                "data_integrity_risk": failure_type in ("staleness", "hallucination"),
                "containment_possible": True,
            },
            "immediate_actions": [
                f"Review the failing span{f' ({failing_span_id})' if failing_span_id else ''} and reproduce locally",
                "Add a guard/fallback for this failure mode before re-running in production",
            ],
            "long_term_recommendations": [
                "Add automated regression tests covering this failure scenario",
                "Connect real Vertex AI credentials to enable live Gemini-powered diagnosis",
            ],
            "repair_feasibility": round(random.uniform(0.55, 0.85), 2),
        }

    def _observation_response(self, prompt: str) -> dict[str, Any]:
        failure_type = (_extract(prompt, r"Failure Type \(pre-labeled\):\s*(\w+)") or "none").lower()
        agent_name = _extract(prompt, r"Agent:\s*(.+?)\s*\(ID:") or "the agent"
        failure_detected = failure_type != "none"
        confidence = round(random.uniform(0.75, 0.95), 2) if failure_detected else round(random.uniform(0.85, 0.98), 2)
        severity = _SEVERITY_BY_FAILURE.get(failure_type, "low")

        return {
            "failure_detected": failure_detected,
            "confidence": confidence,
            "failure_classification": failure_type,
            "severity": severity,
            "anomaly_signals": [],
            "reasoning": (
                f"[DEMO] {agent_name} trace pre-labeled as `{failure_type}`; heuristic and "
                "structural checks are consistent with this classification."
                if failure_detected
                else f"[DEMO] {agent_name} trace completed without error spans or anomaly signals."
            ),
            "affected_components": [],
            "needs_detailed_diagnosis": failure_detected,
        }

    def _validation_response(self) -> dict[str, Any]:
        score = round(random.uniform(0.65, 0.92), 2)
        return {
            "passed": score >= 0.6,
            "score": score,
            "checks": {
                "addresses_root_cause": True,
                "before_after_reasonable": True,
                "test_coverage_adequate": score >= 0.6,
                "risk_acceptable": True,
                "implementable": True,
            },
            "notes": "[DEMO] Repair structure and rationale look consistent with the diagnosed root cause.",
            "test_results": [],
            "recommended_improvements": (
                [] if score >= 0.6 else ["Add an additional test case covering the edge case in the failing span"]
            ),
        }

    def _repair_response(self, prompt: str) -> dict[str, Any]:
        if "## CURRENT PROMPT/INSTRUCTIONS" in prompt:
            return self._prompt_repair(prompt)
        if "Failed Tool:" in prompt:
            return self._tool_repair(prompt)
        return self._orchestration_repair(prompt)

    def _prompt_repair(self, prompt: str) -> dict[str, Any]:
        agent_name = _extract(prompt, r"Agent:\s*(.+)") or "the agent"
        current_prompt = _extract_block(prompt, "## CURRENT PROMPT/INSTRUCTIONS", "## FAILURE EVIDENCE")
        before = current_prompt or f"You are {agent_name}. Complete the user's request using the available tools."
        after = (
            before.rstrip()
            + "\n\n# --- Repaired guidance (added) ---\n"
            + "- Always validate tool outputs before using them in your final answer.\n"
            + "- If a tool call fails or returns no data, state this explicitly instead of guessing.\n"
            + "- Do not repeat the same tool call more than twice; escalate instead."
        )
        return {
            "repair_type": "prompt_edit",
            "title": f"Tighten instructions for {agent_name}",
            "description": "Add explicit grounding, failure-handling, and loop-prevention guidance to the system prompt.",
            "rationale": "[DEMO] The diagnosed root cause traces back to ambiguous/under-specified instructions; adding explicit constraints closes the gap.",
            "before": before,
            "after": after,
            "diff_description": "Appended grounding, error-handling, and loop-prevention rules to the system prompt.",
            "test_cases": [
                {
                    "name": "test_no_fabricated_results",
                    "description": "Agent must not fabricate tool results when a tool call fails",
                    "input_payload": {},
                    "expected_behavior": "Agent reports the tool failure instead of inventing a result",
                    "failure_scenario": "Agent hallucinated a successful tool result after a failure",
                },
                {
                    "name": "test_no_repeated_tool_loop",
                    "description": "Agent must not call the same tool more than twice in a row",
                    "input_payload": {},
                    "expected_behavior": "Agent escalates after two failed attempts",
                    "failure_scenario": "Agent looped on the same tool call",
                },
            ],
            "confidence": round(random.uniform(0.7, 0.88), 2),
            "risk_level": "low",
            "side_effects": ["Slightly longer system prompt increases prompt token usage marginally"],
            "rollback_instructions": "Remove the appended 'Repaired guidance' section to restore the original prompt.",
        }

    def _tool_repair(self, prompt: str) -> dict[str, Any]:
        agent_name = _extract(prompt, r"Agent:\s*(.+)") or "the agent"
        tool_name = _extract(prompt, r"Failed Tool:\s*(\S+)") or "tool"
        tool_error = _extract(prompt, r"Tool Error:\s*(.+)") or "Unknown error"

        before = f"""# Tool: {tool_name}
config = {{
    "timeout_seconds": 30,
    "retry_count": 1,
    "validate_response_schema": False,
}}"""
        after = f"""# Tool: {tool_name} (repaired)
config = {{
    "timeout_seconds": 60,             # increased timeout
    "retry_count": 3,                  # added retries
    "retry_backoff_factor": 2.0,       # exponential backoff
    "validate_response_schema": True,  # reject malformed responses early
    "circuit_breaker_threshold": 5,    # trip breaker after repeated failures
}}"""
        return {
            "repair_type": "tool_config_change",
            "title": f"Harden `{tool_name}` configuration for {agent_name}",
            "description": f"Add retries, backoff, response validation and a circuit breaker to `{tool_name}`.",
            "rationale": f"[DEMO] `{tool_name}` failed with: {tool_error[:200]}. The current config has no retry or validation, so a single transient error fails the whole trace.",
            "before": before,
            "after": after,
            "diff_description": "Added retry/backoff, response validation, and circuit breaker to the tool config.",
            "test_cases": [
                {
                    "name": f"test_{tool_name}_recovers_on_transient_error",
                    "description": f"{tool_name} should recover from a transient failure via retry",
                    "input_payload": {},
                    "expected_behavior": f"{tool_name} succeeds within 3 attempts",
                    "failure_scenario": tool_error[:120],
                }
            ],
            "confidence": round(random.uniform(0.65, 0.85), 2),
            "risk_level": "low",
            "side_effects": ["Increased timeout may slightly slow down failure detection for genuinely broken endpoints"],
            "rollback_instructions": f"Revert `{tool_name}` config to its previous values.",
        }

    def _orchestration_repair(self, prompt: str) -> dict[str, Any]:
        agent_name = _extract(prompt, r"Agent:\s*(.+)") or "the agent"
        before = """# Orchestration loop
while not task_complete:
    result = call_tool(next_tool, args)
    update_state(result)
    # no max-iteration guard, no progress check"""
        after = """# Orchestration loop (repaired)
MAX_ITERATIONS = 8

for iteration in range(MAX_ITERATIONS):
    result = call_tool(next_tool, args)
    if not made_progress(result, previous_state):
        escalate_to_human("No progress after repeated tool calls")
        break
    update_state(result)
    if task_complete:
        break
else:
    escalate_to_human("Max iterations reached without completion")"""
        return {
            "repair_type": "orchestration_fix",
            "title": f"Add iteration guard to {agent_name}'s control loop",
            "description": "Bound the agent's execution loop and escalate when no progress is made.",
            "rationale": "[DEMO] The diagnosed root cause is an unbounded orchestration loop; adding a max-iteration guard and progress check prevents runaway execution.",
            "before": before,
            "after": after,
            "diff_description": "Added MAX_ITERATIONS guard and a progress check with escalation.",
            "test_cases": [
                {
                    "name": "test_loop_terminates_without_progress",
                    "description": "Loop must terminate and escalate if no progress is made across iterations",
                    "input_payload": {},
                    "expected_behavior": "Agent escalates to a human after repeated no-progress iterations",
                    "failure_scenario": "Agent looped indefinitely on the same tool call",
                }
            ],
            "confidence": round(random.uniform(0.68, 0.86), 2),
            "risk_level": "medium",
            "side_effects": ["Tasks that legitimately need more than 8 iterations will now escalate instead of completing"],
            "rollback_instructions": "Remove the MAX_ITERATIONS guard and progress check to restore the original loop.",
        }


def _extract(text: str, pattern: str) -> str | None:
    m = re.search(pattern, text)
    return m.group(1).strip() if m else None


def _extract_block(text: str, start_marker: str, end_marker: str) -> str | None:
    try:
        start = text.index(start_marker) + len(start_marker)
        end = text.index(end_marker, start)
        return text[start:end].strip()
    except ValueError:
        return None
